products:
  - name: "Dream Router"
    url: "https://store.ui.com/collections/unifi-network-unifi-os-consoles/products/dream-router"
  - name: "Cloud Key Gen2 Plus"
    url: "https://store.ui.com/collections/unifi-network-unifi-os-consoles/products/unifi-cloudkey-plus"